[package]

# Note: Semantic Versioning is used: https://semver.org/
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.10.36"
=======
version = "0.10.33"
>>>>>>> abfba5273e (Fresh start, no history)
=======
version = "0.10.33"
>>>>>>> abfba5273e35ca74eb713aa9a0404a6fad7fd5a5

# Description
title = "Isaac Lab Environments"
description="Extension containing suite of environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}

[core]
reloadable = false

[[python.module]]
name = "isaaclab_tasks"
