[package]

# Note: Semantic Versioning is used: https://semver.org/
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.1.8"
=======
version = "0.1.4"
>>>>>>> abfba5273e (Fresh start, no history)
=======
version = "0.1.4"
>>>>>>> abfba5273e35ca74eb713aa9a0404a6fad7fd5a5

# Description
title = "Isaac Lab RL"
description="Extension containing reinforcement learning related utilities."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["robotics", "rl", "wrappers", "learning"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_tasks" = {}

[core]
reloadable = false

[[python.module]]
name = "isaaclab_rl"
